### ISSUE TITLE
Gateway timeout (504) when viewing source file reports

### ISSUE THREAD

**Issue by peace-maker** [lemurheavy/coveralls-public#1757]
In the build report https://coveralls.io/builds/66967692 I cannot view the coverage changes of any file.

https://coveralls.io/builds/66967692/source?filename=pwnlib%2Futil%2Ffiddling.py returns a Gateway time-out error from cloudflare.

**Comment by ndortega** [comment]
I'm also facing the same 504: 

Build: https://coveralls.io/builds/67122849
File: https://coveralls.io/builds/67122849/source?filename=src%2Fextractors.jl

**Comment by jacquelineIO** [comment]
Same here. Also facing this issue https://coveralls.io/builds/67458288

Looks like there is another another issue with the same report https://github.com/lemurheavy/coveralls-public/issues/1751

**Comment by jrfnl** [comment]
Just adding my voice to this too. I've been seeing this for weeks now and it's getting annoying.

```
The web server reported a gateway time-out error.

    Ray ID: 88f8dc14dc779f5e
    Your IP address: 143.xxx.xxx.xxx (for privacy)
    Error reference number: 504
    Cloudflare Location: Amsterdam
```

![image](https://github.com/lemurheavy/coveralls-public/assets/663378/f9106dbc-1f93-4d66-8e4a-b04b7cfac81d)

Pinging @afinetooth as I don't see the presence of the Coveralls team in either of the issues regarding this problem.

**Comment by afinetooth** [comment]
Thanks for reporting everyone. The only thing we have going for us right now in terms of diagnosing this is more frequency lately. We believed these 504s were intermittent and mapped pretty consistently to rolling data center updates at Cloudflare, but are starting to suspect there's a server issue on our end that's escaping monitoring.

Anything you can provide from time, your location, screenshot and/or HAR file could help us figure this out.

Question:
Is there anyone who is experiencing this more than intermittently, where "intermittently" is for more than a 1-2 minute period, more than once/week?

**Comment by afinetooth** [comment]
Also, it would be helpful to know a couple other things, so here's the full list---any of these datapoints helps:

1. Time with time zone?
2. Your location (globally)?
3. Web Request OR API Request?
4. IF Web Request, what URL?
5. Screenshot
6. HAR File (bonus)

**Comment by jrfnl** [comment]
@afinetooth Thanks for picking this up.

This is the additional information I can give you:
* I've been consistently seeing this for the past six weeks (approximately).
* I can access the Coveralls website, the [overview pages](https://coveralls.io/github/PHPCSStandards/PHP_CodeSniffer), even the [individual build pages](https://coveralls.io/builds/67916604).
* However, as soon as I try to view the detailed code coverage of an [individual file](https://coveralls.io/builds/67916604/source?filename=src%2FUtil%2FCommon.php) in a build, I hit this 504 error.

As for your data points:
1. I've been seeing this behaviour consistently at all hours day or night. I'm in the CET timezone.
2. As per the above comment, Amsterdam, The Netherlands, Europe.
3. Web requests only, I don't use API requests.
4. [Example link](https://coveralls.io/builds/67916604/source?filename=src%2FUtil%2FCommon.php), but it is basically any URL for viewing code coverage of an individual file, so URLs ending in `source?filename=<filename>`
5. See https://github.com/lemurheavy/coveralls-public/issues/1757#issuecomment-2152612946
6. What is a HAR file ?

Hope this helps to narrow things down.

**Comment by afinetooth** [comment]
Thanks, @jrfnl! This is all very helpful. 

Interestingly, you're 2/5 people reporting from The Netherlands, 3/5 from central Europe. Anectdotal at this point. If it's nothing to do with the Cloudflare network, then it could scope an issue on our end to a time-of-day.

A [HAR File](https://en.wikipedia.org/wiki/HAR_(file_format)) is basically a log dump from your browser in JSON format. [Here](https://support.zendesk.com/hc/en-us/articles/4408828867098-Generating-a-HAR-file-for-troubleshooting#h_01HRYRY6VQVR5K6SRVAVNQ4XT0) is how to generate one from Chrome (and [other browsers](https://support.zendesk.com/hc/en-us/articles/4408828867098-Generating-a-HAR-file-for-troubleshooting#h_01HRFHNXRB4YH4BMMGN6VEAYWB)).

**Comment by jrfnl** [comment]
@afinetooth Here goes. You'll need to rename the file as GH doesn't allow HAR file uploads.

[20240606-17.04UTC.har.txt](https://github.com/user-attachments/files/15668943/20240606-17.04UTC.har.txt)

**Comment by jrfnl** [comment]
Oh and if it helps, I tested with multiple browsers (Palemoon, Brave) and the issue is not browser related (same result is all browsers).

**Comment by afinetooth** [comment]
@jrfnl Thank you! And thanks for the update. It's good to know the behavior is not browser specific.

**Comment by ndortega** [comment]
@afinetooth 

Thankfully, I'm not facing this issue with newer builds - but this link from an older build has been broken since April 25th of this year and has never returned anything than a 504

1. Easter Daylight Time
2. USA, Orlando, Florida
3. Web Request
4. https://coveralls.io/builds/67122849/source?filename=src%2Fextractors.jl
5. ![Screenshot 2024-06-07 212617](https://github.com/lemurheavy/coveralls-public/assets/22534471/fccc6df2-8fe3-4da7-b7fa-8975d00667b0)

**Comment by afinetooth** [comment]
@ndortega Interesting and helpful. I get a `504` for that URL as well. Perhaps we have a reproducible issue from a location close to us. Thank you.

**Comment by jrfnl** [comment]
@afinetooth If it helps, I just tried the https://coveralls.io/builds/67122849/source?filename=src%2Fextractors.jl and I can reproduce the 504 error from Europe as well, so it is not directly location related.

![image](https://github.com/lemurheavy/coveralls-public/assets/663378/ac49cdc9-9780-4848-87d0-7c8d9def0df5)

**Comment by afinetooth** [comment]
@jrfnl Got it. Thank you!

**Comment by jrfnl** [comment]
@afinetooth Just for arguments sake, I just did another check of that same URL + the example problem link I posted before. This time from Italy and yup, got the 504 again for both pages. So I think that confirms it really isn't location or even IP address related.

![image](https://github.com/lemurheavy/coveralls-public/assets/663378/134e2cf0-368c-44be-bd34-a41618df6d2a)

**Comment by afinetooth** [comment]
@jrfnl Yes, thank you. That seems to be our fully reproducible example, failing from multiple global locations, every time for me. 

<img width="1264" alt="Screenshot 2024-06-12 at 6 26 53 PM" src="https://github.com/lemurheavy/coveralls-public/assets/918667/e226d202-27e6-4a1c-a0de-5576b5b4634f">

And interestingly there is nothing special about that source file. It is not particularly large, for instance:

<img width="966" alt="Screenshot 2024-06-12 at 6 27 22 PM" src="https://github.com/lemurheavy/coveralls-public/assets/918667/8a3c0cc5-b635-43ed-b491-d6807b2cbd7e">

But the problem seems to be scoped to the entire build:
https://coveralls.io/builds/67122849

Because none of the source files are accessible:

<img width="970" alt="Screenshot 2024-06-12 at 6 31 48 PM" src="https://github.com/lemurheavy/coveralls-public/assets/918667/33e32b7c-2313-4aa4-8501-7a379b04cb07">

They all throw `504`s:

<img width="1384" alt="Screenshot 2024-06-12 at 6 32 22 PM" src="https://github.com/lemurheavy/coveralls-public/assets/918667/b15c3d3d-343d-4a76-8434-14bda0b4bb92">

**Comment by ndortega** [comment]
@afinetooth 
I'm also encountering this same issue with my latest builds: https://coveralls.io/builds/68083208

**Comment by afinetooth** [comment]
@ndortega OK, thank you. We'll use your builds for further investigation.

**Comment by shubhammapara** [comment]
Facing the same issue, and getting a gateway timeout.
<img width="1728" alt="SCR-20240716-rhkz" src="https://github.com/user-attachments/assets/f33fbe7e-1c29-4d12-80f1-3e2dd5f703bb">

**Comment by afinetooth** [comment]
@shubhammapara thanks for reporting.

**Update**:
We are continuing to receive reports about this as an intermittent occurrence for some users.

Our only fully reproducible examples remain the couple of builds ([1](https://coveralls.io/builds/67122849) | [2](https://coveralls.io/builds/68083208)) from the [OxygenFramework/Oxygen.jl](https://coveralls.io/github/OxygenFramework/Oxygen.jl) repo, from @ndortega.

Unfortunately, the nature of this issue is such that we cannot gather data on it from our production bug tracking system, --or from logs--, so we're having trouble identifying a pattern and new instances are not shedding new light.

**Correction**:
_We are sourcing the appropriate logs into our APM. I've only now updated my query skills to find them._

To be transparent, while we've made a few efforts to resolve this, we're a small organization and, because the issue is intermittent and affecting only some users, it is difficult for us to prioritize the issue and allocate the time apparently required to resolve it.

While it will stay in our backlog and we will continue making attempts to fix it when we can, if anyone out there is willing to investigate and provide a diagnosis that leads to a fix, we would be happy to offer, in exchange, free service equivalent to one year of our [Org+ plan](https://coveralls.io/pricing#:~:text=ORG%2B,START%20COVERING), which could also be applied as a discount to an existing subscription.

---

P.S. I have been able to consistently load this file from [Build 1](https://coveralls.io/builds/67122849) from [OxygenFramework/Oxygen.jl](https://coveralls.io/github/OxygenFramework/Oxygen.jl):
https://coveralls.io/builds/67122849/source?filename=src%2Fextensions%2Fplotting%2Fwglmakie.jl

Notably, it's a small file (33 lines), but not the smallest in the project:

<img width="555" alt="Screenshot 2024-07-18 at 2 33 36 PM" src="https://github.com/user-attachments/assets/73599afe-98a6-457c-b2cb-ce3bedb769b0">

These other two files, the third and fourth smallest, respectively, load intermittently:

- https://coveralls.io/builds/67122849/source?filename=src%2Fdeprecated.jl
- https://coveralls.io/builds/67122849/source?filename=src%2Fextensions%2Fplotting%2Fbonito.jl

Strangely, I have not gotten the first and second smallest files to load:

- https://coveralls.io/builds/67122849/source?filename=src%2Futil.jl
- https://coveralls.io/builds/67122849/source?filename=src%2FOxygen.jl

No file above 33 lines has loaded for me yet.

**Comment by oir** [comment]
Been observing this issue for a while consistently as well.

File: https://coveralls.io/builds/68844598/source?filename=barkeep%2Fbarkeep.h#L304

Randomly (non exhaustively) checked some past builds in that repo, they all get to the same error page.

**Comment by jrfnl** [comment]
For what it's worth: I can reproduce the issue with @oir's URL as well.

**Comment by afinetooth** [comment]
Thanks, @oir & @jrfnl. I can also confirm receiving the `504` Gateway Timeout error consistently for [that URL](https://coveralls.io/builds/68844598/source?filename=barkeep%2Fbarkeep.h#L304).

**Comment by afinetooth** [comment]
**Just a quick update**:

From other cases recently reported this appears to be intermittent for most of those cases, and, as documented above, there are only a few cases that _consistently_ time out**. Those cases _seem_ to relate to the file size of the file being requested---even though _that_ size is not anywhere near the _general_ size limits for one of our API requests.

Our further investigations recently point to _some_ underlying performance issue.  Unfortunately, nothing straightforward that's triggering an APM alert or showing up in monitoring. We suspect a slow database query, but again, nothing that's showing up in queries _flagged_ as slow by our system that watches those, and, so far, none of the SQL queries underlying these requests troubles the database at all. Therefore, we suspect something _combinatory_. Best guess is a lock on a shared resource.

But we are off any notion that this is originating from our edge service network, beyond of our servers, since we've found evidence of the internal `502` and `499` responses that ultimately result in the `504` Gateway Timeout errors users see in their browsers---even though those errors are being reported from Cloudlflare and tagged with Cloudflare metadata.

** _Of those cases that "consistently" timeout, we have been using [this URL](https://coveralls.io/builds/68844598/source?filename=barkeep%2Fbarkeep.h#L304) for our recent tests. Interestingly, while it times out every time for me, and for my colleagues, we actually see some `200` success responses for this request---not many, but recent ones, mixed in with `502`s and `499`s---in our logs._

**Comment by jsoref** [comment]
tangentially related: It sounds like the timeout values between your side and cloudflare aren't compatible. If I were you, I'd be inclined to reduce the timeouts internally/increase the timeouts externally so that it isn't possible for the internal side to serve a page w/ a 200 where cloudflare's timeout triggers yielding a 504. -- Ideally, doing that your internal monitoring of errors would more closely match what end users see.

**Comment by afinetooth** [comment]
@jsoref thanks for the recommendation. Makes sense. I have updated our internal ticket.

**Comment by mfittko** [comment]
We're seeing this for a very long time now. It seems kinda flaky but there are reports for single file coverage that persistently give 504 errors for us, too.
<img width="741" alt="Screenshot 2024-12-19 at 12 01 03" src="https://github.com/user-attachments/assets/9ff9a3f6-594e-459f-8324-1ed949c19d30" />
With heavy hearts, since we're also experiencing coverage flakiness after switching to parallel CI runners, we're now actively evaluating moving to codecov.

**Comment by mfittko** [comment]
We're seeing this for a very long time now. It seems kinda flaky but there are reports for single file coverage that persistently give 504 errors for us, too.

<img width="741" alt="Screenshot 2024-12-19 at 12 01 03" src="https://github.com/user-attachments/assets/01e634c4-4443-4739-8c6c-66ad44aa82c8" />

With heavy hearts, since we're also experiencing coverage flakiness after switching to parallel CI runners, we're now actively evaluating moving to codecov.

**Comment by afinetooth** [comment]
@mfittko sorry to hear about the separate issue you encountered after switching to parallel CI runners. I'd be happy to help you sort that out if you'd care to open a new issue on [this board](https://github.com/lemurheavy/coveralls-public/issues) (if you're a free tier user). You can also ping me at support@coveralls.io. 

As for this issue, I'm also sorry you're encountering it. It's been extremely difficult for us to resolve as it entails two outside providers beyond our control: (A) GitHub; and (B) our edge service provider (Cloudflare).

**Coveralls data (JSON)**:
As you can see, if you add a `.json` extension to your source file URL, the data coming from Coveralls itself is extremely small, and fast, and is unlikely to ever trip a timeout. For your example, that URL is:
https://coveralls.io/builds/71414916/source.json?filename=lib%2Fspass%2Fsubscription.rb

**External requests**:
For one reason or another, the associated GitHub request (for raw source file contents) and Cloudflare request (which wraps the overall request) sometimes take longer than expected and we are struggling to gain enough control over them to predictably ensure they resolve within Cloudflare's Timeout setting.

**Potential causes, particular to GitHub tokens and end user locations**:
As far as reasons, with GitHub we have seen reasons such as rate limiting/waits and file size constraints; and with Cloudflare, we have noticed other potential causes, such as the customer's location and delayed processing through particular datacenters, typically associated with rolling maintenance, which, when it reroutes traffic for a datacenter, adds time to the request.

**Re: Cloudflare datacenter locations & rerouting**:
I'm sharing a screenshot below of today's [Cloudflare status page]((https://www.cloudflarestatus.com/)) report on rerouting across its global datacenters. If you check the same [status page](https://www.cloudflarestatus.com/) randomly, you'll see this rerouting changing regularly across datacenters:

![Cloudflare rerouting - 2025-01-02 at 11 01 27](https://github.com/user-attachments/assets/7b6008b0-d10c-4984-98e5-06c77059be85)

**Next steps**:
We feel we've reached the limit of the control we can exercise over our part of the chained request cycle, so **we are now tearing that down, again, to see if we can rebuild it for greater reliability**. In addition, we aim to, as much as possible, pass through to end users any errors or delays caused by rate limiting or rerouting that may occur through our provider network.

**Comment by mfittko** [comment]
@afinetooth thanks a lot for digging into the issue and for the detailed response. I'll be taking a deeper look at it tomorrow. As for the separate issue with the flaky reports with combined coveralls builds, we'll also do a more detailed report.

**Comment by jrfnl** [comment]
Not sure what's happening, but after recent updates, this one appears to be back with a vengeance for viewing individual files....

**Comment by afinetooth** [comment]
@jrfnl we had a brief incident this morning that probably exacerbated use cases right near the line of those timeouts. 

We deployed resources to reduce latencies around 8:30am-9am PST that eliminated them by about 9:45a, so that _should_ have reduced these incidents as well. 

If you're still seeing them, please share your build or source file URL(s) and I'll have a look.

**Comment by jrfnl** [comment]
@afinetooth Thanks for the update. Will keep an eye on things and report URLs when I see them.

**Comment by jrfnl** [comment]
@afinetooth Here are a few I saw today:
* https://coveralls.io/builds/72671928/source?filename=src%2FConfig.php
* https://coveralls.io/builds/72691382/source?filename=src%2FRuleset.php
* https://coveralls.io/builds/72668622/source?filename=src%2FTokenizers%2FPHP.php
* https://coveralls.io/builds/72668622/source?filename=src%2FUtil%2FTokens.php

Edit: and another one: https://coveralls.io/builds/72691996/source?filename=src%2FRuleset.php

**Comment by afinetooth** [comment]
@jrfnl Thanks for reporting these.

General conditions must be better because these two (2) are loading for me now, like:

- https://coveralls.io/builds/72668622/source?filename=src%2FUtil%2FTokens.php (833 lines)
- https://coveralls.io/builds/72668622/source?filename=src%2FTokenizers%2FPHP.php (4,050 lines)

**Noting**:
- Both are from the same build.
- The second being of substantial length and more likely to time-out.

Still, these three (3) don't succeed:

- https://coveralls.io/builds/72671928/source?filename=src%2FConfig.php
- https://coveralls.io/builds/72691382/source?filename=src%2FRuleset.php
- https://coveralls.io/builds/72691996/source?filename=src%2FRuleset.php

**Noting**:
- All are from separate builds. 
- I don't see anything in our production bug tracking system for any of those builds.
- All three (3) builds are status: `completed`, so these continue to fall under the general issue.

We make the last of several infrastructure changes this weekend that, while they don't directly address this issue, should shave a little more time off requests (from improved database performance), so I'm hoping we'll get this one as a bonus. If not, the number of source files affected should at least decrease somewhat.

**Comment by mathieuboudreau** [comment]
Problem persists for me

File tried: https://coveralls.io/builds/74527618/source?filename=AxonDeepSeg%2Fmorphometrics%2Fcompute_morphometrics.py

Location: New Brunswick, Canada (Eastern Canada)

**Comment by afinetooth** [comment]
@mathieuboudreau Confirmed, thank you. I have added you to our internal ticket for this.

We're hopeful about fixing this in our next couple of sprints.

**Comment by oleibman** [comment]
I am seeing this problem every time I try to show any file. It is not at all intermittent. Multiple machines, multiple browsers, multiple builds, multiple files.

Time with time zone? 2:18 p.m. Pacific Daylight Time 2025-08-29
Your location (globally)? Palo Alto, California, USA
Web Request OR API Request? Web request
IF Web Request, what URL? https://coveralls.io/builds/75302276/source?filename=src%2FPhpSpreadsheet%2FComment.php

**Comment by oleibman** [comment]
Here is my har file (from about 2:52 p.m. when I attempted this again).
[coveralls.io_Archive \[25-08-29 14-48-14\].har.txt](https://github.com/user-attachments/files/22053833/coveralls.io_Archive.25-08-29.14-48-14.har.txt)

**Comment by afinetooth** [comment]
@oleibman Thanks for the details and the HAR file. We think you're being affected in the same way and for the same reasons as other users here.

The good news is that we are implementing a short-term solution today and tomorrow that _should_ prevent the `504` Timeouts, until we can implement a permanent solution that will take several weeks.

I am hopeful that we can at least prevent the timeouts, if not the long waits for some users. But the permanent fix has a few phases, so we expect to shorten the request times a bit in one of the early phases.

After we implement the immediate fix, I will test some URLs here and continue updating this ticket with status.

**Comment by djeedai** [comment]
Hi-

I've been hitting that 504 consistently on a single repo for a week at least now. I've sent details by email to `support@coveralls.io`. I get the 504 error code on any browser/device/network after some timeout. This seems to be specific to that one repo; I have at least another one working fine. Since our CI is gated with coverage, this effectively means our project is blocked from new commits. Is there any chance someone can have a look please?

Thanks!

**Comment by afinetooth** [comment]
Hi @djeedai. FYI, I just replied to your support request to support@coveralls.io.

> Is there any chance someone can have a look please?

Had a look and you appear to be affected in the same fashion as other users—no underlying errors, etc. 

Hard to say what is different about your affected repo. To some extent, it's only reasonable to say it's the size / volume of related data. In your case, I also verified that Cloudflare re-routing is not involved. (I tested while both Dublin and Cork datacenters were fully operational.)

I am hopeful that in the next 24-48 hrs, we can finally reduce, if not fully eliminate, the incidents of these intermittent 504 Timeouts on the primary pages where customers are known to experience them, including:

- Source Files pages (subject of this issue)
- Repo pages
- Add Repos pages

We recommend following this issue for updates, or subscribing to our [status page](https://status.coveralls.io/) for updates on [this incident](https://status.coveralls.io/incidents/6vf9p6wf702z).

**Comment by djeedai** [comment]
Thanks a lot for the update @afinetooth !

**Comment by afinetooth** [comment]
**Quick update**:
We are still working on this short-term fix but should be finished today.

**Comment by HebaruSan** [comment]
Hi @afinetooth, thanks for your work. I don't know when "today" ends for you, but should we expect it to work yet? Or hold off a bit?

**Comment by mathieuboudreau** [comment]
> Problem persists for me
> 
> File tried: https://coveralls.io/builds/74527618/source?filename=AxonDeepSeg%2Fmorphometrics%2Fcompute_morphometrics.py
> 
> Location: New Brunswick, Canada (Eastern Canada)

Still not working for our repo too

**Comment by djeedai** [comment]
Same, no change for https://coveralls.io/github/djeedai/bevy_tweening?branch=main

**Comment by afinetooth** [comment]
Yes, apologies. We have not deployed to production yet as there were some surprises in our STAGING environment that we're still trying to resolve.

We are in `PDT` (`US/Los Angeles`) time zone, BTW.

When I get to my desk I'll check status and post an update.

**Comment by afinetooth** [comment]
I have a small update on status: 

**TL;DR**: Still WIP, but max request times verified at `100s` after config changes.

**Details**:
While we have not pushed our full, short-term fix to `production` yet, and are still working out an issue discovered in `staging`, we did deploy some initial configuration changes to `production` (which have been verified) to ensure that all Coveralls-side timeouts are longer than our edge network timeout (Cloudflare at `100s`). 

This just means that if anyone's previous requests were timing out at between `60s`-`100s` before, they have +`40s` headroom now, and those requests should now succeed.

**Requests `>100s` still fail**:
That said, I tested these two examples from recent posters and both continue to fail at exactly `100s`:

- https://coveralls.io/builds/74527618/source?filename=AxonDeepSeg%2Fmorphometrics%2Fcompute_morphometrics.py  (@mathieuboudreau)
- https://coveralls.io/github/djeedai/bevy_tweening?branch=main (@djeedai)

We are continuing to work on deploying our fix to production. I will post updates here.

**Comment by oleibman** [comment]
I am now receiving 504's whenever Github tries to upload to Coveralls.

**Comment by makskustomer** [comment]
Same

**Comment by dbason** [comment]
Same issue in Jenkins uploading reports:
```
coveralls.exception.CoverallsException: Could not submit coverage: 504 Server Error: Gateway Timeout for url: https://coveralls.io/api/v1/jobs
```

**Comment by jrfnl** [comment]
Just saw this one again: https://coveralls.io/builds/75459328/source?filename=src%2FConfig.php#L442
(seeing it regularly though, but just thought I'd include a link to a file from a recent PR where I saw it)

**Comment by afinetooth** [comment]
@dbason @oleibman The `504` from our API, when uploading a coverage report is unrelated to this issue and was temporary yesterday.

It should be fully resolved now, so please try again and let me know if you experience otherwise.

**Comment by afinetooth** [comment]
@oleibman just added you to the above ^^.

**Comment by oleibman** [comment]
Agreed - uploading coverage to github appears to work fine today.

**Comment by qkdreyer** [comment]
I am now also receiving 504's whenever Github tries to upload to Coveralls.

<img width="1552" height="987" alt="Image" src="https://github.com/user-attachments/assets/4e5d7f48-04e4-42d8-b460-029b56bf5bfd" />

**Comment by afinetooth** [comment]
Hi @qkdreyer. Thanks for reporting your `504`. That should be resolved now.

Just FYI, a `504` on an upload is a different issue from this one, in that it has a different root cause, and won't be resolved by this fix. 

The good news is that, in contrast to the `504`s here, the `504`s on uploads issue is quicker to resolve upon occurrence and usually short-lived--so always worth trying again later.

That said, reporting those is helpful, since it could give us an early heads up--though I recommend doing so in a new issue.

**Comment by giamberinigiulia** [comment]
Is anyone else experiencing this today?
I’m having trouble running the following Maven goal on GitHub Actions: _org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report_
The job fails with: I/O operation failed: _Report submission to Coveralls API failed with HTTP status 504: Gateway Timeout (Coveralls API internal error)_
I also tried visiting [https://coveralls.io](https://coveralls.io) directly, but the site itself returned a 504 Gateway Timeout, which suggests the problem may be with the Coveralls API/service rather than my setup.

**Comment by HebaruSan** [comment]
File detail pages were working well yesterday, but now they're timing out again:

- <https://coveralls.io/builds/75463513/source?filename=Core%2FNet%2FNetFileCache.cs>
- <https://coveralls.io/builds/75463513/source?filename=GUI%2FModel%2FGUIMod.cs>

... EDIT: Confirming what @afinetooth says below that this was a temporary problem that has since resolved. Thanks again for your work.

**Comment by afinetooth** [comment]
Hi @giamberinigiulia and @HebaruSan. The `504` errors you experienced this morning should be resolved now. 

**Explanation**: Those `504` errors were due to temporary traffic spikes from outlier repos. Almost like an attack, but not intentional, we have some users who submit upload requests for repos with abnormally massive parallel builds (up to 1200 uploads per CI build). While we have contacted most of those users and restricted processing on those repos, in some cases the upload requests are still being sent to our HTTP servers and must be handled there. This morning, two builds from one such repo spread across all of our HTTP servers at once, putting them under duress and causing many competing requests to timeout with `504s`. 

@HebaruSan those Source File Page URLs should be working again for you (I don't think either one meets the requirements to consistently generate a `504` response.) Your `504` errors had the same (temporary) root cause as @giamberinigiulia's: The `504s` were being returned by our HTTP servers, which were temporarily overloaded by requests from an outlier repo. 

**More info**:
We posted a [status page update](https://status.coveralls.io/incidents/6vf9p6wf702z) this morning about the period today when we received a more than normal amount of `504` reports, from `6:45a-7:45a PDT`, which resolved itself after that. Both of your `504s` fell within that period.

Re: "traffic spikes from outlier repos" the [postmortem](https://status.coveralls.io/incidents/3jpvbjkwf1d1) from [this incident](https://status.coveralls.io/incidents/3jpvbjkwf1d1) explains that situation. It had been surfacing as `503` (“This website is under heavy load”) errors for several days, but then, after we implemented an intermediate solution, significantly less but still occasional incidents of overload began surfacing as `504` timeout errors. That's the type of error you experienced this morning.

**Comment by afinetooth** [comment]
Thanks to everyone here for your patience as we continue trying to deliver our solution to the `504` errors you're experiencing with some of your [Source File Pages](https://docs.coveralls.io/app-ui#source-file-page), [ADD REPOS Pages](https://docs.coveralls.io/app-ui#the-add-repos-page), and even [Repo Page](https://docs.coveralls.io/app-ui#repo-page)s. 

It turns out that our "quick" solution generated many more edge case bugs than expected and has not yet made it out of testing in our staging environments. We believe we're finally wrapping up the last of those fixes today and hope to deploy today near EOD PDT, allowing for a few hours of observation. 

I will post here and on our [status page](https://status.coveralls.io/) as soon as we've deployed to production.

**Comment by jrfnl** [comment]
@afinetooth I'm sorry you all keep having trouble, but everything is down again (and has been for a few hours), uploads fail, reporting back doesn't work etc etc.

Even the build overview page for repos is now showing that 504. (Example: https://coveralls.io/repos/418090/builds?page=2)

**Comment by mrwormhole** [comment]
just seems to be getting worse on CI, switching to codecov open source version seems to be the solution

**Comment by mathieuboudreau** [comment]
Is there anything that can be done on our repo's side to help improve this ? Is this because our projects have too many lines, too long of a history of pushing coverage reports, etc?

**Comment by mathieuboudreau** [comment]
Huh, today I noticed that our push to coveralls failed, is this related or another issue? https://github.com/axondeepseg/axondeepseg/actions/runs/17722305909/job/50356765657

**Comment by oleibman** [comment]
Although my pushes to coveralls failed all through the weekend, they seem to be working now.

**Comment by afinetooth** [comment]
@jrfnl @mrwormhole @mathieuboudreau @oleibman 

## Update on upload `504s`:
We've taken aggressive action this morning to hopefully avoid further `504s` on uploads until we are able to close _this_ ticket and move on to the one for _uploads_ specifically. 

### Immediate mitigating action
We have:
- Doubled our regular web server fleet (already doubled from normal, since we started seeing this issue)
- Extended autoscaling to our web layer, so that our fleet can double again when NGINX response times exceed set levels.

### Background
As mentioned earlier in this ticket, the problem is occasional surges of connected upload requests from outlier repos (750–1250 uploads per build). We can usually handle 1–2 of these at once, depending on build size, but 3–4 XL requests arriving together can saturate all servers. 

We’ve reached out to these users and already paused processing for the offending repos. However, until they stop sending requests entirely, our frontline HTTP servers still have to absorb the load.

**EU and Asia effects**:
As a small team based in PDT (Los Angeles), we’re least able to respond quickly to spikes overnight (10p–6a PDT). Unfortunately, the two main outlier repos are in APAC, which makes those hours the worst overlap of triggers and team coverage. ([WorldTime Buddy](https://www.worldtimebuddy.com/) for timezone comparisons.)

### Why this should work
- Doubling our capacity for these XL requests should push `504` conditions up to 6-8 simultaneous XL requests, which we haven't seen yet.
- Autoscaling should put this same strategy "on tap." We've chosen short, 5-minute look-back windows that should help us respond to sudden spikes.

### Next steps
These infra changes are in place now, so we hope frequency has already dropped. That said:

1. Please notify us here if you continue experiencing any `504s` on uploads.
2. As we learn more about autoscaling in our web layer, we can tune our settings to respond better.

**Comment by afinetooth** [comment]
@mathieuboudreau 

> Is there anything that can be done on our repo's side to help improve this ? Is this because our projects have too many lines, too long of a history of pushing coverage reports, etc?

No. History of uploads is not an issue. Unless you happen to have what we consider an outlier repo (50+ uploads per build)—_I don't suspect you do or I would recognize it_—there is probably nothing to do from your end outside of scheduling your CI build times, which is likely impractical. 

Unfortunately, the issue is probably one of timing / time zones. Just based on the build time of the failed example build below, it looks like you're positioned for the [worst overlap of triggers and team coverage](https://github.com/lemurheavy/coveralls-public/issues/1757#issuecomment-3292941507:~:text=EU%20and%20Asia,for%20timezone%20comparisons.).

But, even without human response, we expect our latest infra changes to mitigate the effects in your window now.

> Huh, today I noticed that our push to coveralls failed, is this related or another issue? 
> https://github.com/axondeepseg/axondeepseg/actions/runs/17722305909/job/50356765657

Yes, same error. Related.

**Comment by ChrisE217** [comment]
Experiencing 504s again today.

<img width="381" height="112" alt="Image" src="https://github.com/user-attachments/assets/4e4a0c2f-742b-45ea-a8a2-4a9fb31acf67" />

<img width="2032" height="1124" alt="Image" src="https://github.com/user-attachments/assets/8b31f695-1afb-4b3c-bafd-38192e50e454" />

**Comment by afinetooth** [comment]
Thanks for reporting @ChrisE217 

Should be resolved now. We had an autoscale failure but caught an alert and resolved around 6:30a PDT.

We are still focused on resolving both sides of this issue. We hope to release more changes today.

Will update here.

**Comment by jsoref** [comment]
@afinetooth when things calm down, can you improve the output here:

> Error: Bad response: 504 error code: 504

... isn't the most helpful of messages (no url; the second `error code: 504` added no value on top of the first `504` ...)

**Comment by oleibman** [comment]
I am now receiving 500 Internal Service Error on uploads.

**Comment by afinetooth** [comment]
@oleibman we are not seeing `504s` or the context that would lead to them right now. A `500` could be several other causes.

Can you please share the API response / error from your CI build log?

**Comment by afinetooth** [comment]
@jsoref Thanks for the feedback. Can you help me with the **action** (ie. upload or `POST`) and **endpoint** (ie. `api/v1/jobs`) from which you're receiving that error?

**Comment by oleibman** [comment]
@afinetooth 
I don't think there's much information I can give. Here's what the log has to say:
```
Coverage:  97.73% (12811/13108)
Collect git info
Read environment variables
Dump submitting json file: /home/runner/work/PHPWord/PHPWord/build/coveralls-upload.json
File size: 1,744.31 kB
Submitting to https://coveralls.io/api/v1/jobs
Server error occurred. status: 500 Internal Server Error
Build processing error.
elapsed time: 1.277 sec memory: 10.00 MB
Error: Process completed with exit code 1.
```
Possibly you can find more relevant information at https://github.com/PHPOffice/PHPWord/actions/runs/17928565428/job/50980631118?pr=2567
It is the PhpUnit 8.3 step which uploads to Coveralls. I had several successful runs earlier in the day.

**Comment by afinetooth** [comment]
@oleibman I see. You are using the community-created Coveralls [Language Integration for PHP](https://docs.coveralls.io/php) called [php-coveralls](https://github.com/php-coveralls/php-coveralls).

Because we don't maintain that integration (only our [Official Integrations](https://docs.coveralls.io/integrations#official-integrations)), I can't speak to the nature of the error except to say that a `500` error is a bit of a catchall. The `POST` body likely failed parsing but we weren't able to tell why from a variety of reasons. 

I was able to find an associated error in our production bug tracking system, which indicates a `401` in our underlying request to the GitHub API on your behalf:

```
GET https://api.github.com/repos/oleibman/PHPWord/commits/25d640f7f99e66eda1d86e3aa9279f2d5f082f14/pulls?per_page=100: 401 - Bad credentials
```

My guess was that your repo owner's token has expired, but checking your [repo settings](https://coveralls.io/github/oleibman/PHPWord/settings) indicated the owner's original user account had actually been _deleted_ (same difference):

<img width="655" height="627" alt="Image" src="https://github.com/user-attachments/assets/f7d02426-3933-4594-82d0-ac760019319a" />

I made your account (`oleibman`) the **repo owner**:

<img width="647" height="126" alt="Image" src="https://github.com/user-attachments/assets/c91fc2c1-437b-4996-9625-b373030623bd" />

### Two recommendations to future-proof your setup:

1. Switch to one of our [Official Integrations](https://docs.coveralls.io/integrations#official-integrations) (in your case, the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action)) so we can support your full toolchain going forward ([choose](https://github.com/marketplace/actions/coveralls-github-action#:~:text=format,formats%20list.) `format: clover` for PHP); and
2. Migrate to our [New Github Integration](https://coveralls.io/new-github-integration-beta), which is based on a GitHub App and does not rely on user tokens; which means you'll no longer need to manage a **repo owner**, or add the [Coveralls Commenter Bot](https://github.com/coveralls) to your org/repos.

**Comment by jsoref** [comment]
@afinetooth my comment was in reference to this: https://github.com/lemurheavy/coveralls-public/issues/1757#issuecomment-3312076135

I'm not currently noticing anything beyond everyone else's comments.

**Comment by afinetooth** [comment]
@oleibman wanted to let you know we have resolved those intermittent `500` errors yesterday, and, apologies, it turned out to be infra related, so nothing to do or change on the client side.

We always still recommended our official integrations for full toolchain support, but if what you're using is working then 👍 .

**Comment by KevinEady** [comment]
I'm also having 504s when viewing source file reports when viewing the files from the _build_. It works when viewing files from the _job_ though.

The coverage upload was successful on `2025-09-25T20:18:36Z` via GitHub CI using the `coverallsapp/github-action@master` GitHub Action: https://github.com/polserver/polserver/actions/runs/18019387792/job/51272658343?pr=818#step:22:30

Build https://coveralls.io/builds/75706712 links to https://coveralls.io/builds/75706712/source?filename=pol-core%2Fbscript%2Fcompiler%2Fastbuilder%2FValueBuilder.cpp#L136 which gives a 504

Job https://coveralls.io/jobs/172009224 links to https://coveralls.io/jobs/172009224/source_files/8153384650 (which is the same `pol-core/bscript/compiler/astbuilder/ValueBuilder.cpp` source file as above) and succeeds.

EDIT: seems to have resolved

**Comment by oleibman** [comment]
Problem had been fixed, but I am now getting a 500 just going to https://coveralls.io/

**Comment by rapito** [comment]
> Experiencing 504s again today.
> 
> <img alt="Image" width="381" height="112" src="https://private-user-images.githubusercontent.com/26201156/491590888-4e4a0c2f-742b-45ea-a8a2-4a9fb31acf67.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4OTQ5MjEsIm5iZiI6MTc1ODg5NDYyMSwicGF0aCI6Ii8yNjIwMTE1Ni80OTE1OTA4ODgtNGU0YTBjMmYtNzQyYi00NWVhLWE4YTItNGE5ZmIzMWFjZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI2VDEzNTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YjAyNzUwMGIyM2VhMjZiNDNkNmZmYzQwOWY1M2FlMDVjYjY1MWNkYjA3NzViMDE2ZmQzMzI2ODYwM2IzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6fSJ34PkOTgppT7LgQMzNSbFORhgyzPEtJ7QOpUBksM"> <img alt="Image" width="2000" height="1124" src="https://private-user-images.githubusercontent.com/26201156/491590560-8b31f695-1afb-4b3c-bafd-38192e50e454.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4OTQ5MjEsIm5iZiI6MTc1ODg5NDYyMSwicGF0aCI6Ii8yNjIwMTE1Ni80OTE1OTA1NjAtOGIzMWY2OTUtMWFmYi00YjNjLWJhZmQtMzgxOTJlNTBlNDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI2VDEzNTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZjg3Y2I0OTdmYjY4ZGY2OTRiNjk2ODM0Yzg3YTI4NzdkMDVkZDQ0OWU3Mzg4MTY0ODlmYTE3ZjRmZWZkYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CDfAHDWA26jIm8Dza1t5UQgyZwCoEw1LhiUkH5wC8R8">

Came to bump this as well, having the same issue just trying to access a private repo.

**Comment by afinetooth** [comment]
@rapito Thanks for reporting. The issue was resolved around `6:15am PDT`.

We are actively monitoring, and will continue on mitigations until we can put an end to these. 

You can track status here:
https://status.coveralls.io/ ([current incident](https://status.coveralls.io/incidents/qrwpyt8h4vf1))

**Two things**:

1. If you are experiencing `put 504s`—in particular `504` errors of coverage uploads, please report in [this issue](https://github.com/lemurheavy/coveralls-public/issues/1824); and you can follow the same issue for updates. We'll do our best to circle back here and other issues. 
2. The most helpful report details, right now, are a **timestamp**, **or at least timeframe**, on your error, and any **Cloudflare Ray ID** you may have received with it.

---

**References**:
- Tracking issue: https://github.com/lemurheavy/coveralls-public/issues/1824
- Status Page: https://status.coveralls.io/
- Incident: https://status.coveralls.io/incidents/qrwpyt8h4vf1

**Comment by KevinEady** [comment]
Hi @afinetooth ,

Viewing source file reports, https://coveralls.io/builds/75716844/source?filename=pol-core%2Fbscript%2Fcompiler%2Fastbuilder%2FValueBuilder.cpp#L136 gives 504:

On `Sat, 27 Sep 2025 08:58:42 GMT`:
```
Ray ID: 9859cb884e1d339b
Error reference number: 504
Cloudflare Location: Berlin
```

On `Sat, 27 Sep 2025 09:00:42 GMT`:
```
Ray ID: 9859ce74fb7fd81e
Error reference number: 504
Cloudflare Location: Berlin
```

On `Sat, 27 Sep 2025 13:00:55 GMT`:
```
Ray ID: 985b2e547b451931
Error reference number: 504
Cloudflare Location: Berlin
```

**Comment by afinetooth** [comment]
Thanks, @KevinEady.

**Comment by HebaruSan** [comment]
Suggest pinning this issue to the top of the issues list to make it easier to check in and see if there have been any updates when the issue starts happening again (and to reduce duplicates as more and more users encounter this problem for the first time).

**Comment by oleibman** [comment]
504's again just trying to go to coveralls.io, for at least the last 30 minutes.

**Comment by oleibman** [comment]
I can get to status.coveralls.io however. Despite the fact that nothing else has been working for at least 2 hours, it reports all systems are operational and no incidents have been reported today. Both of those statements seem wrong.

**Comment by afinetooth** [comment]
@oleibman Can you do me a favor and share the time when the `504s` occurred for you? You location, and any Cloudflare Ray IDs for your requests would also be helpful.

We have drastically reduced the `504` incidents during _our_ overnight and weekend hours (PDT / GMT -7), and do not have a record of servers "losing comms" this past weekend, which is our trigger to scale, reboot or replace servers to keep the incident window to a minimum.

That said, it's still _very_ possible that one or more servers throw `504s` before we get that trigger, so knowing your _time_, and especially any _Cloudflare Ray ID_ for your requests will help us trace them. 

Knowing your _location_ is helpful since we can see if traffic was being rerouted around your nearest Cloudflare datacenter, which adds time to requests and can be a temporary reason for `504s`.

**Comment by oleibman** [comment]
Things are working normally since I filed that report. I am in Palo Alto, California. The incidents happened on Friday Oct. 3 between 2:00 pm and 4:00 pm PDT for me; I don't know when they ended (possibly Friday night or Saturday morning). I will try to include the Cloudflare Ray Id if it happens again (which I hope your are close to preventing), but I didn't capture it 5 days ago.

**Comment by afinetooth** [comment]
@oleibman Great, thank you. 

We have managed to drastically reduce the occurrence of these `504s` with improved alerting, and are in progress on an infra upgrade that we think will fully address occurrences of `504s` until we're able to address the root causes of issues with key requests with more _ideal_ solutions.

Infra upgrade will be in place by this Fri, Oct 17, so you should notice the improved stability.

**Comment by afinetooth** [comment]
### Update:
We performed **infrastructure upgrades** this week that we believe will eliminate `504s` whose cause is not rooted in outlier-sized data inherent to specific orgs, projects, files or requests.

We completed the upgrades yesterday and have been **monitoring** for the past **18 hrs** with **zero occurrences of `504` errors**.

### Seeking updates on your experiences

Per the subject of _this_ issue, we are specifically interested _here_ in new reports of **`504` errors from [source file pages](https://docs.coveralls.io/app-ui#source-file-page)**. (There is a tracking issue for `504` errors on coverage uploads and more _general_ cases [here](https://github.com/lemurheavy/coveralls-public/issues/1824).). 

If you've already reported a case here, you can assume we will be testing it and looking into whether it matches an "outlier" case. For instance, @jrfnl, we have restested https://coveralls.io/builds/67122849/source?filename=src%2Fextractors.jl, which still throws a `504` so we are looking deeper into the request to find out why/how it timed out. 

#### More details:

While we have not fully implemented planned optimizations for source file pages, we have increased per-worker processing resources by 2x and fleet-wide capacity by 6x, so we hope this will eliminate the majority of current cases. We believe most previous timeouts occurred when worker threads exceeded available RAM and began paging to disk, so we hope the increased capacity will avoid that.

#### Thanks

Thanks for your patience as we continue trying to eliminate this error type.

**Comment by afinetooth** [comment]
@jrfnl Update:

Really confused / disappointed to realize this file is only 154 lines long:
https://coveralls.io/builds/67122849/source?filename=src%2Fextractors.jl

Recent tests were with a ~14K line file, which threw a `504` prior to our infra upgrade, but now renders:
https://coveralls.io/builds/66763023/source?filename=src/taosdump.c

Blows my hypothesis about outliers being the only remaining cases. We are tracing the request again to see if we can understand what is causing the timeout. 

~14K lines vs. 154 lines! Obviously something else unrelated to file size.

**Comment by jrfnl** [comment]
@afinetooth I appreciate you are trying to analyse the remaining issues, however, the above aren't files from any of my projects.

https://coveralls.io/builds/67916604/source?filename=src%2FUtil%2FCommon.php was one of mine (and still shows 504 when I request it now).

Here's a comment of mine which shows another set of problem files: https://github.com/lemurheavy/coveralls-public/issues/1757#issuecomment-2719364135 - the 3rd and 4th now succeed, the 1st, 2nd and 5th link still show 504s.

This one also still yields a 504 (reported on Sept 9): https://coveralls.io/builds/75459328/source?filename=src%2FConfig.php#L442

**Comment by jrfnl** [comment]
Just encountered a 504 on viewing the source for a changed file from a recent build (couple of days old): https://coveralls.io/builds/75935811/source?filename=PHPCompatibility%2FSniffs%2FClasses%2FRemovedClassesSniff.php

**Comment by mathieuboudreau** [comment]
After being a coveralls user for 7+ years, I'm really considering to stop using it for my projects because this issue that has extended on for years for me. If I'm unable to see file coverage diffs, it's no longer a useful tool for me. 

>https://coveralls.io/builds/74527618/source?filename=AxonDeepSeg%2Fmorphometrics%2Fcompute_morphometrics.py

Is still timing out for me

**Comment by afinetooth** [comment]
@jrfnl Thanks for the correction. Apologies, I know your projects by now and should have realized you don't have any Julia code. 

In any case, I _have_ also been tracking the other URLs you mentioned that aren't resolved by the infra upgrades. 

Current best theory: In _addition_ to file size as a cause (files >10K lines, ~1/3 cases), there's probably a bug in our code that renders the colorization and marginalia in source file reports--likely due to a dependency conflict from an upgrade in the past 12-18 months--which isn't throwing an error, but still causes the rendering to hang until the timeout threshold is reached.

Optimizing that rendering is the goal of our permanent fix for this issue, but we weren't aware of the need to address any bugs; so these smaller files with persistent 504s should help as test cases.

**Comment by oleibman** [comment]
New 504 this morning.

https://coveralls.io/builds/76071046/source?filename=src%2FPhpSpreadsheet%2FReader%2FXls%2FListFunctions.php#L213

The web server reported a gateway time-out error.

    Ray ID: 9921b8142e7c1017
    Your IP address: 165.225.243.113
    Error reference number: 504
    Cloudflare Location: Los Angeles

**Comment by afinetooth** [comment]
Thanks @oleibman!

@mathieuboudreau completely understand were you're coming from. I hope you'll hang in there with us a little longer as we have probably just identified the last factor causing this issue and will be working on it until we can resolve it.

**Comment by HebaruSan** [comment]
Getting one right now at <https://coveralls.io/builds/76112461/source?filename=Core%2FIO%2FModuleInstaller.cs>

```
    Ray ID: 9932132629f2e895
```

... and now it works. I'll leave this comment in case there are still logs or traces that might give insight into the issue.

**Comment by afinetooth** [comment]
HI @HebaruSan. I am able to view that source file report. 

Sometimes, these are network-related and in those cases eventually clear themselves—usually quickly, especially if it's just a hiccup and not the request being routed around your nearest data center while it's down for maintenance (in those cases, it's still usually a matter of minutes).

This suggests your file doesn't meet the conditions that are still causing `504s`.

**Comment by HebaruSan** [comment]
Hi @afinetooth, thanks for the response. I'm not sure what you mean about "doesn't meet the conditions that are still causing 504s", as ~~a~~ many 504s definitely did happen; _some_ condition caused it. When you say "network-related," are you referring to something within your (Coveralls') own network?

**Comment by jrfnl** [comment]
Here's one I just ran into: https://coveralls.io/builds/76389163/source?filename=src%2FStandards%2FSquiz%2FSniffs%2FControlStructures%2FSwitchDeclarationSniff.php

```
Ray ID: 99c162d56b379887
Your IP address: 31.*.*.*
Error reference number: 504
Cloudflare Location: Amsterdam
```

**Comment by oleibman** [comment]
New 504 just encountered.
https://coveralls.io/builds/76431308/source?filename=src%2FPhpSpreadsheet%2FWriter%2FHtml.php#L1341
The web server reported a gateway time-out error.

    Ray ID: 99d422de6ee5aab7
    Your IP address: 165.225.243.101
    Error reference number: 504
    Cloudflare Location: San Jose

**Comment by jsoref** [comment]
- https://github.com/lemurheavy/coveralls-public/issues/1757#issuecomment-3437521069
https://coveralls.io/builds/76112461/source?filename=Core%2FIO%2FModuleInstaller.cs

Ray ID: 99d63950ebeb74a5
Your IP address: 184.*
Error reference number: 504
Cloudflare Location: Toronto

- https://github.com/lemurheavy/coveralls-public/issues/1757#issuecomment-3421340541
https://coveralls.io/builds/74527618/source?filename=AxonDeepSeg%2Fmorphometrics%2Fcompute_morphometrics.py

Ray ID: 99d63a9459bcaa96
Your IP address: 184.*
Error reference number: 504
Cloudflare Location: Toronto

- https://github.com/lemurheavy/coveralls-public/issues/1757#issuecomment-3419191808
https://coveralls.io/builds/75935811/source?filename=PHPCompatibility%2FSniffs%2FClasses%2FRemovedClassesSniff.php

Ray ID: 99d63ab02a26aa96
Your IP address: 184.*
Error reference number: 504
Cloudflare Location: Toronto

**Comment by afinetooth** [comment]
Thanks for the additional reports @jrfnl @oleibman @jsoref.

**Comment by oleibman** [comment]
Almost there, but problems continue. It is very frustrating. Here's a new one from today. The report is uploaded correctly (https://coveralls.io/builds/76605983), but, when I try to drill down on "New Missed Lines in Diff" by clicking on its one File link:
```
The web server reported a gateway time-out error.

    Ray ID: 9a2196a3f8afebe2
    Your IP address: 165.225.243.101
    Error reference number: 504
    Cloudflare Location: San Jose
```

**Comment by oleibman** [comment]
Still unable to drill down. Starting from https://coveralls.io/builds/76863068 and clicking on the one link for "Coverage Changed":
```
The web server reported a gateway time-out error.

    Ray ID: 9ab19f3e3d30236d
    Your IP address: 165.225.243.88
    Error reference number: 504
    Cloudflare Location: San Jose

```

**Comment by afinetooth** [comment]
Hi @oleibman and everyone else who's posted here recently—thanks again for the updates and your patience on this issue.

I want to let you know that your updates aren’t being lost in a void. We’re currently pushing through a couple of end-of-year projects, but this `504` timeout problem is still on our short list. The current plan is to optimize how the source file pages are rendered so that large files (or more accurately, specifically _complex_ files) load quickly and reliably. Once those changes are shipped, we expect them to significantly reduce—and hopefully eliminate—the 504s you’re seeing.

I’ll update here once we start work, and again when we have something live to test. In the meantime, if you hit any new examples or patterns that might help us reproduce, feel free to drop them here.

Thanks again for hanging in there with us.

**Comment by mathieuboudreau** [comment]
> After being a coveralls user for 7+ years, I'm really considering to stop using it for my projects because this issue that has extended on for years for me. If I'm unable to see file coverage diffs, it's no longer a useful tool for me.
> 
> > https://coveralls.io/builds/74527618/source?filename=AxonDeepSeg%2Fmorphometrics%2Fcompute_morphometrics.py
> 
> Is still timing out for me

The issue is still unresolved for our repo with no improvements following the recent changes.

Recent build: https://coveralls.io/builds/76899769/source?filename=AxonDeepSeg%2Fads_napari%2F_widget.py

**Comment by isaacbrodsky** [comment]
We have an example of this issue happening consistently for uber/h3#1111 - https://coveralls.io/builds/77037692/source?filename=src%2Fh3lib%2Flib%2Flocalij.c

**Comment by jrfnl** [comment]
Ran into another one just now: https://coveralls.io/builds/76709426/source?filename=src%2FUtil%2FTokens.php

```
The web server reported a gateway time-out error.

Ray ID: 9b1f721b1e51b8d0
Your IP address: x.x.x.x
Error reference number: 504
Cloudflare Location: Amsterdam
```

**Comment by oleibman** [comment]
Still happening. https://coveralls.io/builds/77114496/source?filename=src%2FPhpSpreadsheet%2FReader%2FHtml.php#L763
```
The web server reported a gateway time-out error.

    Ray ID: 9b4b5c940ea1327e
    Your IP address: 165.225.243.72
    Error reference number: 504
    Cloudflare Location: San Jose
```
Are you any closer to getting this solved????

**Comment by oleibman** [comment]
Having reported several incidents where I couldn't "drill down", I am pleased to report a case where I could:
https://coveralls.io/builds/77165328
Maybe things are fixed now, or, if not, perhaps you can use this to see why it succeeded when others didn't.

**Comment by afinetooth** [comment]
Thanks, @oleibman. 

Unfortunately the issue is still open. It's been intermittent / random since first discovered. The mitigations we've applied so far have isolated it to fewer cases, but we have a long-term fix—basically a full rewrite—that we think will resolve it for all cases. While we've completed a few of the related dependencies, we're still working on that.

**Comment by webbnh** [comment]
[A module from our previous PR](https://coveralls.io/builds/78525605/source?filename=sync2jira%2Fdownstream_issue.py) loads fine.

[The same module from our most recent PR times out](https://coveralls.io/builds/78601355/source?filename=sync2jira%2Fdownstream_issue.py):
> Ray ID: 9e624bd7c9099008
> Your IP address: 70.105.251.51
> Error reference number: 504
> Cloudflare Location: Boston

Time with time zone:  2026-04-02T19:44:39+00:00
Your location (globally):  Northeast U.S.
Web Request OR API Request:  Web site
IF Web Request, what URL:  see hyperlinks
Screenshot:  hopefully the quoted text is sufficient
HAR File:  [coveralls.io.har.json](https://github.com/user-attachments/files/26447981/coveralls.io.har.json)

**Comment by afinetooth** [comment]
Thanks for [reposting](https://github.com/lemurheavy/coveralls-public/issues/1846) here, @webbnh.

**Comment by webbnh** [comment]
Thanks for offering the service, and for free, no less!  It's really valuable, so I'm happy to help keep it working.

**Comment by afinetooth** [comment]
Thanks @webbnh. And thanks for the extra pattern, that helps a lot!

**Comment by webbnh** [comment]
Here's the next one I hit:
> Ray ID: 9ec44219e9283762
Your IP address: 70.105.251.51
Error reference number: 504
Cloudflare Location: Boston

Time with time zone: 14 Apr 2026 13:08:07 -0400
Your location (globally): Northeast U.S.
Web Request OR API Request: Web Request
IF Web Request, what URL: http://coveralls.io/builds/78873419/source?filename=sync2jira%2Fupstream_issue.py
Screenshot: hopefully the quoted text is sufficient

Let me know if you really want the HAR file...I assume I can generate one on demand.  😞

**Comment by afinetooth** [comment]
Thank you, @webbnh!

**Comment by webbnh** [comment]
Here's the next one.

> Ray ID: 9ecd9ea75d9b37a2
Your IP address: 24.179.121.0
Error reference number: 504
Cloudflare Location: Ashburn

Time with time zone: 15 Apr 2026 16:19:28 -0400
Your location (globally): Northeast U.S.
Web Request OR API Request: Web Request
IF Web Request, what URL: https://coveralls.io/builds/78901165/source?filename=sync2jira%2Fupstream_issue.py
Screenshot: hopefully the quoted text is sufficient

Let me know if you really want the HAR file....

**Comment by webbnh** [comment]
Here's the next one (three, actually):
> Ray ID: 9f2fd31bec19553b
Your IP address: 24.179.121.0
Error reference number: 504
Cloudflare Location: Ashburn

https://coveralls.io/builds/79106316/source?filename=sync2jira%2Fdownstream_issue.py

> Ray ID: 9f2fd3224c3f553b
Your IP address: 24.179.121.0
Error reference number: 504
Cloudflare Location: Ashburn

https://coveralls.io/builds/79106316/source?filename=sync2jira%2Fdownstream_pr.py

> Ray ID: 9f2fd3310c8e553b
Your IP address: 24.179.121.0
Error reference number: 504
Cloudflare Location: Ashburn

https://coveralls.io/builds/79106316/source?filename=sync2jira%2Fintermediary.py
